name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    test:
        environment: CI
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@main
        - name: Set up Python 3.8
          uses: actions/setup-python@v1
          with:
              python-version: 3.8
        - name: Install dependencies
          run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
              pip install pylint
        - name: Analysing the code with pylint
          run: |
              pylint -s n main.py
        - name: update Docker image
          if: ${{ github.event_name == 'push' || github.event.pull_request.merge }}
          env:
            DOCKER_USERNAME: 'yevzman'
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          run: |
              sudo docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
              sudo docker build --tag yevzman/telegram_bot .
              sudo docker push yevzman/telegram_bot